from django.urls import path
from .views import (
    create_user_view,
    authenticate_user,
    logout_user,
    index,
    ticket_detail_view,
    update_ticket_view,
    delete_ticket,
    create_review,
    review_detail,
    update_review,
    delete_review,
    # user_followers,
    # user_following,
    follow_user,
    create_ticket,
    ticket_list_view,
    logout_view,
    followers_view,
    unfollow_user,
    create_combined_ticket_review,
    user_following_view,
    abonnement_view,
    user_tickets_view,
    search_tickets_view,
    flux,
    create_reviewstand,
)

urlpatterns = [
    path("", index, name="index"),
    path("create_user/", create_user_view, name="create_user"),
    path("login/", authenticate_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("create_ticket/", create_ticket, name="create_ticket"),
    path("ticket/<int:ticket_id>/", ticket_detail_view, name="ticket_detail"),
    path("ticket/<int:ticket_id>/update/", update_ticket_view, name="update_ticket"),
    path("ticket/<int:ticket_id>/delete/", delete_ticket, name="delete_ticket"),
    path("ticket/<int:ticket_id>/create_review/", create_review, name="create_review"),
    path("review/<int:review_id>/", review_detail, name="review_detail"),
    path("review/<int:review_id>/update/", update_review, name="update_review"),
    path("review/<int:review_id>/delete/", delete_review, name="delete_review"),
    path("follow_user/", follow_user, name="follow_user"),
    path("ticket_list/", ticket_list_view, name="ticket_list"),
    path("logout/", logout_view, name="logout"),
    path("followers/", followers_view, name="followers"),
    path("unfollow_user/", unfollow_user, name="unfollow_user"),
    path(
        "create_combined_ticket_review/",
        create_combined_ticket_review,
        name="create_combined_ticket_review",
    ),
    path("abonnement/", abonnement_view, name="abonnement"),
    path("user_tickets/", user_tickets_view, name="user_tickets"),
    path("search_tickets/", search_tickets_view, name="search_tickets"),
    path("flux/", flux, name="flux"),
    path("create_reviewstand/", create_reviewstand, name="create_reviewstand"),
]
