# Generated by Django 4.2.2 on 2023-07-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("litreviewApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
