# Generated by Django 4.2.2 on 2023-07-09 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("litreviewApp", "0002_alter_review_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="reviewer",
            new_name="created_by",
        ),
        migrations.RemoveField(
            model_name="review",
            name="review_text",
        ),
    ]
