# Generated by Django 4.2.2 on 2023-07-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("litreviewApp", "0003_rename_reviewer_review_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollows",
            name="followed_tickets",
            field=models.ManyToManyField(
                related_name="followers", to="litreviewApp.ticket"
            ),
        ),
    ]
