# Generated by Django 4.2.2 on 2023-07-18 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("litreviewApp", "0004_userfollows_followed_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollows",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfollows",
            name="followed_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_by_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
