# Generated by Django 4.2.2 on 2023-07-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("litreviewApp", "0005_alter_userfollows_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketReviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="litreviewApp.review",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="litreviewApp.ticket",
                    ),
                ),
            ],
        ),
    ]
