# Generated by Django 4.2.2 on 2023-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("litreviewApp", "0007_alter_ticket_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
