# Generated by Django 4.2.2 on 2023-08-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("litreviewApp", "0011_remove_review_ticket_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="ticket_optional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="optional_reviews",
                to="litreviewApp.ticket",
            ),
        ),
    ]
