# Generated by Django 4.2.2 on 2023-08-22 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("litreviewApp", "0012_review_ticket_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="ticket_optional",
        ),
    ]
