# Generated by Django 4.2.2 on 2023-08-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("litreviewApp", "0013_remove_review_ticket_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="litreviewApp.ticket",
            ),
        ),
    ]
